import type { Metadata } from "next";
import { Montserrat, Kumar_One_Outline } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"], display: 'swap' });
const kumarOneOutline = Kumar_One_Outline({
  weight: ["400"],
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-kumar-one'
});

export const metadata: Metadata = {
  title: 'Sarath "Delta" Singh',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} ${kumarOneOutline.variable} w-screen h-screen`}>{children}</body>
    </html>
  );
}
